spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_DB_PORT:5432}/mydb
spring.datasource.username=user
spring.datasource.password=password
spring.rabbitmq.host=localhost
spring.rabbitmq.port=${RabbitMQ_PORT:5672}
spring.jpa.hibernate.ddl-auto=update
spring.rabbitmq.template.default-receive-queue=notification-queue
spring.rabbitmq.listener.simple.auto-startup=true       
